// Generated by CoffeeScript 1.7.1
describe("Action Controller", function() {
  beforeEach(function() {
    return this.controller = new ActionController;
  });
  return it("should build a valid console command object from a console command string", function() {
    var result;
    result = this.controller.build_from_input("CLEAR");
    expect(result.command).toEqual("<clear_command>");
    result = this.controller.build_from_input("RUN");
    expect(result.command).toEqual("<run_command>");
    result = this.controller.build_from_input("INFO");
    expect(result.command).toEqual("<info_command>");
    result = this.controller.build_from_input("LIST");
    return expect(result.command).toEqual("<list_command>");
  });
});
