// Generated by CoffeeScript 1.7.1
describe("The BASIC program object", function() {
  beforeEach(function() {
    return this.program = new BasicProgram;
  });
  it("should create a BasicProgram object", function() {
    var bp;
    expect(this.program).toBeDefined;
    bp = jasmine.any(BasicProgram);
    expect(this.program).toEqual(bp);
    return expect(this.program.lines).toEqual(jasmine.any(Array));
  });
  it("should add lines to the BASIC program", function() {
    this.program.addline(10, '10 REM WELCOME TO GRANDPA BASIC 80');
    this.program.addline(20, '20 $T = "JOHN R SCHMIDT"');
    this.program.addline(30, '30 INPUT "DISPLAY NAME (Y/N)?";$Y');
    this.program.addline(40, '40 IF $Y<>"Y" THEN 100');
    this.program.addline(50, '50 PRINT "WRITTEN BY "+$T');
    this.program.addline(100, '100 PRINT "OK BYE"');
    this.program.addline(999, '999 END');
    expect(this.program.lines).toContain({
      "ln_no": 10,
      "text": '10 REM WELCOME TO GRANDPA BASIC 80'
    });
    expect(this.program.lines).toContain({
      "ln_no": 20,
      "text": '20 $T = "JOHN R SCHMIDT"'
    });
    expect(this.program.lines).toContain({
      "ln_no": 30,
      "text": '30 INPUT "DISPLAY NAME (Y/N)?";$Y'
    });
    expect(this.program.lines).toContain({
      "ln_no": 40,
      "text": '40 IF $Y<>"Y" THEN 100'
    });
    expect(this.program.lines).toContain({
      "ln_no": 50,
      "text": '50 PRINT "WRITTEN BY "+$T'
    });
    expect(this.program.lines).toContain({
      "ln_no": 100,
      "text": '100 PRINT "OK BYE"'
    });
    expect(this.program.lines).toContain({
      "ln_no": 999,
      "text": '999 END'
    });
    this.program.addline(50, '50 PRINT "PROGRAM AUTHOR: "+$T');
    expect(this.program.lines).toContain({
      "ln_no": 50,
      "text": '50 PRINT "PROGRAM AUTHOR: "+$T'
    });
    return expect(this.program.lines).not.toContain({
      "ln_no": 50,
      "text": '50 PRINT "WRITTEN BY "+$T'
    });
  });
  it("should fetch lines from the BASIC program", function() {
    this.program.addline(10, '10 REM WELCOME TO GRANDPA BASIC 80');
    this.program.addline(20, '20 $T = "JOHN R SCHMIDT"');
    this.program.addline(30, '30 INPUT "DISPLAY NAME (Y/N)?";$Y');
    this.program.addline(40, '40 IF $Y<>"Y" THEN 100');
    this.program.addline(50, '50 PRINT "WRITTEN BY "+$T');
    this.program.addline(100, '100 PRINT "OK BYE"');
    this.program.addline(999, '999 END');
    expect(this.program.fetch(10).text).toEqual('10 REM WELCOME TO GRANDPA BASIC 80');
    expect(this.program.fetch(20).text).toEqual('20 $T = "JOHN R SCHMIDT"');
    expect(this.program.fetch(30).text).toEqual('30 INPUT "DISPLAY NAME (Y/N)?";$Y');
    expect(this.program.fetch(40).text).toEqual('40 IF $Y<>"Y" THEN 100');
    expect(this.program.fetch(50).text).toEqual('50 PRINT "WRITTEN BY "+$T');
    expect(this.program.fetch(100).text).toEqual('100 PRINT "OK BYE"');
    return expect(this.program.fetch(999).text).toEqual('999 END');
  });
  return it("should remove lines from the BASIC program", function() {
    this.program.addline(10, '10 REM WELCOME TO GRANDPA BASIC 80');
    this.program.addline(20, '20 $T = "JOHN R SCHMIDT"');
    this.program.addline(30, '30 INPUT "DISPLAY NAME (Y/N)?";$Y');
    this.program.addline(40, '40 IF $Y<>"Y" THEN 100');
    this.program.addline(50, '50 PRINT "WRITTEN BY "+$T');
    this.program.addline(100, '100 PRINT "OK BYE"');
    this.program.addline(999, '999 END');
    this.program.remove(30);
    this.program.remove(40);
    this.program.remove(100);
    expect(this.program.fetch(10).text).toEqual('10 REM WELCOME TO GRANDPA BASIC 80');
    expect(this.program.fetch(20).text).toEqual('20 $T = "JOHN R SCHMIDT"');
    expect(this.program.fetch(30)).toEqual({});
    expect(this.program.fetch(40)).toEqual({});
    expect(this.program.fetch(50).text).toEqual('50 PRINT "WRITTEN BY "+$T');
    expect(this.program.fetch(100)).toEqual({});
    return expect(this.program.fetch(999).text).toEqual('999 END');
  });
});
