describe "BASIC Console", ->

  beforeEach ->
    @console = new BasicConsole
    @console.log_chars = true


  it "should print a character at a given location", ->
    @console.ch("A",0,0)
    expect(@console.msg).toEqual("A [0,0]")
    @console.ch("B",0,10)
    expect(@console.msg).toEqual("B [0,10]")
    @console.ch("C",0,20)
    expect(@console.msg).toEqual("C [0,20]")
    @console.ch("D",0,30)
    expect(@console.msg).toEqual("D [0,30]")
    @console.ch("E",0,40)
    expect(@console.msg).toEqual("E [0,40]")
    @console.ch("F",0,50)
    expect(@console.msg).toEqual("F [0,50]")
    @console.ch("G",0,60)
    expect(@console.msg).toEqual("G [0,60]")
    @console.ch("H",1,5)
    expect(@console.msg).toEqual("H [1,5]")
    @console.ch("I",1,15)
    expect(@console.msg).toEqual("I [1,15]")
    @console.ch("J",1,25)
    expect(@console.msg).toEqual("J [1,25]")
    @console.ch("K",1,35)
    expect(@console.msg).toEqual("K [1,35]")
    @console.ch("L",1,45)
    expect(@console.msg).toEqual("L [1,45]")
    @console.ch("M",1,55)
    expect(@console.msg).toEqual("M [1,55]")
    @console.ch("N",2,0)
    expect(@console.msg).toEqual("N [2,0]")
    @console.ch("O",2,10)
    expect(@console.msg).toEqual("O [2,10]")
    @console.ch("P",2,20)
    expect(@console.msg).toEqual("P [2,20]")
    @console.ch("Q",2,30)
    expect(@console.msg).toEqual("Q [2,30]")
    @console.ch("R",2,40)
    expect(@console.msg).toEqual("R [2,40]")
    @console.ch("S",2,50)
    expect(@console.msg).toEqual("S [2,50]")
    @console.ch("T",2,60)
    expect(@console.msg).toEqual("T [2,60]")
    @console.ch("U",3,5)
    expect(@console.msg).toEqual("U [3,5]")
    @console.ch("V",3,15)
    expect(@console.msg).toEqual("V [3,15]")
    @console.ch("W",3,25)
    expect(@console.msg).toEqual("W [3,25]")
    @console.ch("X",3,35)
    expect(@console.msg).toEqual("X [3,35]")
    @console.ch("Y",3,45)
    expect(@console.msg).toEqual("Y [3,45]")
    @console.ch("Z",3,55)
    expect(@console.msg).toEqual("Z [3,55]")
    @console.ch("0",4,20)
    expect(@console.msg).toEqual("0 [4,20]")
    @console.ch("1",5,21)
    expect(@console.msg).toEqual("1 [5,21]")
    @console.ch("2",6,22)
    expect(@console.msg).toEqual("2 [6,22]")
    @console.ch("3",7,23)
    expect(@console.msg).toEqual("3 [7,23]")
    @console.ch("4",8,24)
    expect(@console.msg).toEqual("4 [8,24]")
    @console.ch("5",9,25)
    expect(@console.msg).toEqual("5 [9,25]")
    @console.ch("6",10,26)
    expect(@console.msg).toEqual("6 [10,26]")
    @console.ch("7",11,27)
    expect(@console.msg).toEqual("7 [11,27]")
    @console.ch("8",12,28)
    expect(@console.msg).toEqual("8 [12,28]")
    @console.ch("9",13,29)
    expect(@console.msg).toEqual("9 [13,29]")

#    @console.ch("",)
#    expect(@console.msg).toEqual(" []")
#    @console.ch("",)
#    expect(@console.msg).toEqual(" []")
#    @console.ch("",)
#    expect(@console.msg).toEqual(" []")


