// Generated by CoffeeScript 1.7.1
describe("Console scrolling", function() {
  beforeEach(function() {
    this.console = new BasicConsole;
    return this.scroll = this.console.scroll;
  });
  it("should add lines to the scroll buffer as they are printed", function() {
    var n, _i;
    expect(this.scroll.length).toEqual(0);
    this.console.println("10 X=100");
    expect(this.scroll.length).toEqual(1);
    expect(this.scroll[0]).toEqual("10 X=100");
    this.console.println("20 Y=33");
    expect(this.scroll.length).toEqual(2);
    expect(this.scroll[1]).toEqual("20 Y=33");
    this.console.println("30 Z=888");
    expect(this.scroll.length).toEqual(3);
    expect(this.scroll[2]).toEqual("30 Z=888");
    this.console.println("40 M=X+Y");
    expect(this.scroll.length).toEqual(4);
    expect(this.scroll[3]).toEqual("40 M=X+Y");
    this.console.println("50 W=M/Z");
    expect(this.scroll.length).toEqual(5);
    expect(this.scroll[4]).toEqual("50 W=M/Z");
    for (n = _i = 1; _i <= 15; n = ++_i) {
      this.console.println("88 REM FILLER LINE");
    }
    return expect(this.scroll.length).toEqual(20);
  });
  return it("should move lines towards top of 'screen' as lines are added at bottom", function() {
    var n, _i;
    expect(this.scroll.length).toEqual(0);
    this.console.println("10 X=100");
    this.console.println("20 Y=33");
    this.console.println("30 Z=888");
    this.console.println("40 M=X+Y");
    this.console.println("50 W=M/Z");
    for (n = _i = 1; _i <= 15; n = ++_i) {
      this.console.println("88 REM FILLER LINE");
    }
    expect(this.scroll.length).toEqual(20);
    this.console.println("210 X=110");
    expect(this.scroll.length).toEqual(21);
    expect(this.scroll[20]).toEqual("210 X=110");
    this.console.println("220 X=120");
    expect(this.scroll.length).toEqual(22);
    expect(this.scroll[21]).toEqual("220 X=120");
    this.console.println("230 X=130");
    expect(this.scroll.length).toEqual(23);
    expect(this.scroll[22]).toEqual("230 X=130");
    this.console.println("240 X=140");
    expect(this.scroll.length).toEqual(23);
    expect(this.scroll[22]).toEqual("240 X=140");
    expect(this.scroll[0]).toEqual("20 Y=33");
    expect(this.scroll[1]).toEqual("30 Z=888");
    this.console.println("250 X=150");
    expect(this.scroll.length).toEqual(23);
    expect(this.scroll[22]).toEqual("250 X=150");
    expect(this.scroll[0]).toEqual("30 Z=888");
    expect(this.scroll[1]).toEqual("40 M=X+Y");
    this.console.println("260 X=160");
    expect(this.scroll.length).toEqual(23);
    expect(this.scroll[22]).toEqual("260 X=160");
    expect(this.scroll[0]).toEqual("40 M=X+Y");
    return expect(this.scroll[1]).toEqual("50 W=M/Z");
  });
});
