// Generated by CoffeeScript 1.6.3
describe("Test of GB80 Grandpa Basic browser code", function() {
  return describe("Test GB80 Console functions", function() {
    beforeEach(function() {
      return this.console = new Gb80Console;
    });
    return it("should create a Gb80Console object", function() {
      expect(this.console).toBeDefined;
      return expect(this.console).toEqual(jasmine.any(Gb80Console));
    });
  });
});
