// Generated by CoffeeScript 1.7.1
describe("Console line buffer", function() {
  beforeEach(function() {
    return this.buffer = new LineBuffer;
  });
  it("should create a LineBuffer object", function() {
    expect(this.buffer).toBeDefined;
    expect(this.buffer).toEqual(jasmine.any(LineBuffer));
    return expect(this.buffer.get_text()).toEqual("");
  });
  it("should fetch the line buffer text", function() {
    this.buffer.text = '10 REM WELCOME TO GRANDPA BASIC 80';
    return expect(this.buffer.get_text()).toEqual('10 REM WELCOME TO GRANDPA BASIC 80');
  });
  it("should set the line buffer text", function() {
    this.buffer.set_text('10 REM WELCOME TO GRANDPA BASIC 80');
    return expect(this.buffer.get_text()).toEqual('10 REM WELCOME TO GRANDPA BASIC 80');
  });
  return xit("should load text from the console object into the line buffer object", function() {
    this.console.addline('10 REM WELCOME TO GRANDPA BASIC 80');
    this.console.load_line_buffer(0);
    expect(this.buffer.get_text()).toEqual('10 REM WELCOME TO GRANDPA BASIC 80');
    this.console.load_line_buffer(7);
    return expect(this.buffer.get_text()).toEqual("");
  });
});
