// Generated by CoffeeScript 1.7.1
describe("Numeric expression object", function() {
  it("should create a NumericExpression object", function() {
    var nxp;
    nxp = new NumericExpression(["<numeric_expression>", "<numeric_literal>", 3, "<num_exp_end>"]);
    return expect(nxp).toEqual(jasmine.any(NumericExpression));
  });
  return xit("should build a NumericExpression object from a numeric expression 'parse object'", function() {
    var expected, nmx, po;
    po = ["<numeric_expression>", "<number_variable>", "X", "<num_exp_end>"];
    expected = {
      expr: "<var>",
      name: "X"
    };
    nmx = new NumericExpression(po);
    expect(nmx).toEqual(jasmine.any(NumericExpression));
    expect(nmx.expr).toEqual("<var>");
    expect(nmx.name).toEqual("X");
    po = ["<numeric_expression>", "<numeric_literal>", 42, "<num_exp_end>"];
    expected = {
      expr: "<num>",
      value: 42
    };
    nmx = new NumericExpression(po);
    expect(nmx).toEqual(jasmine.any(NumericExpression));
    expect(nmx.expr).toEqual("<num>");
    return expect(nmx.name).toEqual(42);
  });
});
