// Generated by CoffeeScript 1.7.1
describe("Numeric string formatter", function() {
  beforeEach(function() {
    this.helpers = new InterpreterHelpers;
    return this.num_form = this.helpers.num_form;
  });
  return it("should format a number to a string with no more than 8 digits", function() {
    var str;
    str = this.num_form.num_to_str(0);
    expect(str).toEqual("0");
    str = this.num_form.num_to_str(1);
    expect(str).toEqual("1");
    str = this.num_form.num_to_str(-1);
    expect(str).toEqual("-1");
    str = this.num_form.num_to_str(488);
    expect(str).toEqual("488");
    str = this.num_form.num_to_str(3.1416);
    expect(str).toEqual("3.1416");
    str = this.num_form.num_to_str(1 / 3);
    expect(str).toEqual("0.3333333");
    str = this.num_form.num_to_str(3 / 7);
    expect(str).toEqual("0.4285714");
    str = this.num_form.num_to_str(30 / 7);
    expect(str).toEqual("4.2857142");
    str = this.num_form.num_to_str(3000 / 7);
    expect(str).toEqual("428.57142");
    str = this.num_form.num_to_str(12345678);
    expect(str).toEqual("12345678");
    str = this.num_form.num_to_str(0.1);
    expect(str).toEqual("0.1");
    str = this.num_form.num_to_str(0.1234567);
    expect(str).toEqual("0.1234567");
    str = this.num_form.num_to_str(0.12345678);
    return expect(str).toEqual("0.1234567");
  });
});
