// Generated by CoffeeScript 1.7.1
describe("Numeric variable register", function() {
  it("should register a new variable", function() {
    var num_vars;
    num_vars = new NumericVariableRegister;
    num_vars.add_var("X");
    expect(num_vars.defined("X")).toEqual("yes");
    num_vars.add_var("A3");
    expect(num_vars.defined("A3")).toEqual("yes");
    num_vars.add_var("H");
    expect(num_vars.defined("H")).toEqual("yes");
    num_vars.add_var("K0");
    expect(num_vars.defined("K0")).toEqual("yes");
    num_vars.add_var("V9");
    expect(num_vars.defined("V9")).toEqual("yes");
    expect(num_vars.defined("Y")).toEqual("no");
    expect(num_vars.defined("M2")).toEqual("no");
    expect(num_vars.defined("P3")).toEqual("no");
    expect(num_vars.defined("Q")).toEqual("no");
    return expect(num_vars.defined("A4")).toEqual("no");
  });
  return it("should set and get the value for a variable", function() {
    var num_vars;
    num_vars = new NumericVariableRegister;
    num_vars.set("J", 17);
    num_vars.set("P0", 918.64428);
    num_vars.set("M", 2);
    expect(num_vars.get("J")).toEqual(17);
    expect(num_vars.get("P0")).toEqual(918.64428);
    expect(num_vars.get("M")).toEqual(2);
    expect(num_vars.get("L")).toEqual(0);
    return expect(num_vars.get("Z4")).toEqual(0);
  });
});
