// Generated by CoffeeScript 1.7.1
describe("Test numeric expression classes", function() {
  describe("Test NumericExpression superclass", function() {
    beforeEach(function() {
      return this.num_exp = new NumericExpression;
    });
    return it("should create a NumericExpression object", function() {
      expect(this.num_exp).toBeDefined;
      expect(this.num_exp).toEqual(jasmine.any(NumericExpression));
      return expect(this.num_exp.type).toEqual(null);
    });
  });
  return describe("Test Scalar class", function() {
    beforeEach(function() {
      return this.scalar = new Scalar;
    });
    return it("should create a Scalar object", function() {
      expect(this.scalar).toBeDefined;
      expect(this.scalar).toEqual(jasmine.any(Scalar));
      return expect(this.scalar.type).toEqual("<scalar>");
    });
  });
});
