// Generated by CoffeeScript 1.7.1
describe("Test numeric expression parser", function() {
  beforeEach(function() {
    return this.parser = new NumericExpressionParser;
  });
  return describe("Test numeric expression parser", function() {
    return it("should create a NumericExpressionParser object", function() {
      expect(this.parser).toBeDefined;
      return expect(this.parser).toEqual(jasmine.any(NumericExpressionParser));
    });
  });
});
