// Generated by CoffeeScript 1.7.1
describe("Numeric expression object", function() {
  return it("should create a NumericExpression object", function() {
    var nxp;
    nxp = new NumericExpression(["<numeric_literal>", 3]);
    return expect(nxp).toEqual(jasmine.any(NumericExpression));
  });
});
