// Generated by CoffeeScript 1.7.1
describe("Test BASIC program line functions", function() {
  beforeEach(function() {
    return this.line = new BasicProgramLine(10, '10 REM WELCOME TO GRANDPA BASIC 80');
  });
  return it("should create a BasicProgramLine object", function() {
    expect(this.line).toBeDefined;
    expect(this.line).toEqual(jasmine.any(BasicProgramLine));
    expect(this.line.ln_no).toEqual(10);
    expect(this.line.text).toEqual('10 REM WELCOME TO GRANDPA BASIC 80');
    return expect(this.line.tokens).toEqual(jasmine.any(Array));
  });
});
