// Generated by CoffeeScript 1.7.1
describe("Syntax rules", function() {
  beforeEach(function() {
    return this.parser = new SyntaxRules;
  });
  return it("should create a SyntaxRules object", function() {
    return expect(this.parser).toEqual(jasmine.any(SyntaxRules));
  });
});
